// Seed script: creates an admin and a member, plus a sample project & tasks.
// Usage: from server/ folder run `npm run seed`
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const User = require('../models/User');
const Project = require('../models/Project');
const Task = require('../models/Task');

async function run() {
  await connectDB();

  console.log('Wiping existing collections...');
  await Promise.all([
    User.deleteMany({}),
    Project.deleteMany({}),
    Task.deleteMany({}),
  ]);

  const admin = await User.create({
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'admin123',
    role: 'admin',
  });
  const member = await User.create({
    name: 'Member User',
    email: 'member@example.com',
    password: 'member123',
    role: 'member',
  });

  const project = await Project.create({
    name: 'Sample Project',
    description: 'Auto-generated by seed script',
    owner: admin._id,
    members: [admin._id, member._id],
  });

  await Task.create([
    {
      title: 'Set up CI/CD',
      description: 'Initialize GitHub Actions or Railway hooks',
      project: project._id,
      createdBy: admin._id,
      assignedTo: admin._id,
      status: 'in_progress',
      priority: 'high',
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Design dashboard UI',
      project: project._id,
      createdBy: admin._id,
      assignedTo: member._id,
      status: 'todo',
      priority: 'medium',
      dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // already overdue
    },
    {
      title: 'Write README',
      project: project._id,
      createdBy: admin._id,
      status: 'done',
      priority: 'low',
    },
  ]);

  console.log('\nSeed complete.');
  console.log('Admin login:   admin@example.com / admin123');
  console.log('Member login:  member@example.com / member123');
  await mongoose.connection.close();
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
